version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn clean test
      - store_test_results:
          path: /home/circleci/project/target/surefire-reports
          file: index.html
workflows:
  version: 2
  build_and_test:
    jobs:
      - test